enum ICON_TYPES {
  SHUT_DOWN = 'SHUT_DOWN',
  STAR = 'STAR',
  DONE_ALL = 'DONE_ALL',
  CLOSE = 'CLOSE',
  FILE = 'FILE',
  USER = 'USER',
  PLAY = 'PLAY',
  ELLIPSIS = 'ELLIPSIS',
  LOADING = 'LOADING',

  DOC = 'DOC',
  WAVE1 = 'WAVE1',
  WAVE2 = 'WAVE2',
  WAVE3 = 'WAVE3',
  CIRCLE_WAVE = 'CIRCLE_WAVE',
  PLAY_VIDEO = 'PLAY_VIDEO',
  FACE = 'FACE',
  CROSS = 'CROSS',
  AIR_PLANE = 'AIR_PLANE',

  ARROW_RIGHT = 'ARROW_RIGHT',
  ARROW_LEFT = 'ARROW_LEFT',
  ARROW_UP = 'ARROW_UP',
  ARROW_DOWN = 'ARROW_DOWN',

  PLUS_CIRCLE = 'PLUS_CIRCLE',
  SEARCH = 'SEARCH',
  DELETE = 'DELETE',
}
// chevron_down
export { ICON_TYPES };
